# Generated by Django 5.2 on 2025-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_address_user_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Adresse email unique requise pour la récupération de mot de passe', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CASHIER', 'Caissier')], default='CASHIER', help_text="Rôle de l'utilisateur dans le système", max_length=20),
        ),
    ]
