# Generated by Django 5.2 on 2025-08-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du fournisseur', verbose_name='Description'),
        ),
    ]
