# Generated by Django 5.2 on 2025-08-03 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom complet de l'entreprise fournisseur", max_length=200, verbose_name='Nom du fournisseur')),
                ('contact_person', models.CharField(help_text='Nom de la personne responsable', max_length=150, verbose_name='Personne de contact')),
                ('email', models.EmailField(help_text='Adresse email principale', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Numéro de téléphone principal', max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format: '+999999999'. 15 chiffres maximum.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('address', models.TextField(help_text='Adresse physique du fournisseur', verbose_name='Adresse complète')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('tax_number', models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50, verbose_name='Numéro TVA')),
                ('payment_terms', models.CharField(default='30 jours', help_text='Ex: 30 jours, paiement comptant, etc.', max_length=100, verbose_name='Conditions de paiement')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Limite de crédit accordée au fournisseur', max_digits=12, verbose_name='Limite de crédit (€)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text='Notes internes sur le fournisseur', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
    ]
