# Generated by Django 5.2 on 2025-08-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale_saleitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Élément de vente', 'verbose_name_plural': 'Éléments de vente'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text="Téléversement d'une image (toutes extensions supportées)", null=True, upload_to='products/', verbose_name='Image du produit'),
        ),
    ]
